import unittest
from avl.tree import Tree


class TestTree(unittest.TestCase):

    def setUp(self) -> None:
        self.t = Tree()

    def tearDown(self) -> None:
        del self.t


    def test_single_insert(self) -> None:
        self.assertTrue(self.t.insert(2))
        self.assertIsNotNone(self.t.root)
        self.assertEqual(self.t.root, 2)

        self.assertTrue(self.t.insert(1))
        self.assertIsNotNone(self.t.root.lchild)
        self.assertEqual(self.t.root.lchild, 1)
        self.assertIsNotNone(self.t.root.lchild.parent)
        self.assertEqual(self.t.root.lchild.parent, self.t.root)

        self.assertTrue(self.t.insert(3))
        self.assertIsNotNone(self.t.root.rchild)
        self.assertEqual(self.t.root.rchild, 3)
        self.assertIsNotNone(self.t.root.rchild.parent)
        self.assertEqual(self.t.root.rchild.parent, self.t.root)

        self.assertFalse(self.t.insert(2))
        self.assertFalse(self.t.insert(1))
        self.assertFalse(self.t.insert(3))


    def test_multi_insert(self) -> None:
        self.assertTrue(self.t.insert(2, 1, 3))

        self.assertIsNotNone(self.t.root)
        self.assertEqual(self.t.root, 2)

        self.assertIsNotNone(self.t.root.lchild)
        self.assertEqual(self.t.root.lchild, 1)
        self.assertIsNotNone(self.t.root.lchild.parent)
        self.assertEqual(self.t.root.lchild.parent, self.t.root)

        self.assertIsNotNone(self.t.root.rchild)
        self.assertEqual(self.t.root.rchild, 3)
        self.assertIsNotNone(self.t.root.rchild.parent)
        self.assertEqual(self.t.root.rchild.parent, self.t.root)

        self.assertTrue(self.t.insert(2, 1, 3, 4))

        self.assertIsNotNone(self.t.root.rchild.rchild)
        self.assertEqual(self.t.root.rchild.rchild, 4)
        self.assertIsNotNone(self.t.root.rchild.rchild.parent)
        self.assertEqual(self.t.root.rchild.rchild.parent, self.t.root.rchild)

        self.assertFalse(self.t.insert(2, 1, 3))


    def test_balanced_insert(self) -> None:
        self.t.insert(2, 1, 4, 3, 6, 5, 7)

        n2 = self.t.find(2)
        n1 = self.t.find(1)
        n4 = self.t.find(4)
        n3 = self.t.find(3)
        n6 = self.t.find(6)
        n5 = self.t.find(5)
        n7 = self.t.find(7)
        self.assertIsNotNone(n2)
        self.assertIsNotNone(n1)
        self.assertIsNotNone(n4)
        self.assertIsNotNone(n3)
        self.assertIsNotNone(n6)
        self.assertIsNotNone(n5)
        self.assertIsNotNone(n7)

        self.assertEqual(self.t.root, n4)

        self.assertEqual(n4.lchild, n2)
        self.assertEqual(n2.parent, n4)
        self.assertEqual(n2.lchild, n1)
        self.assertEqual(n1.parent, n2)
        self.assertEqual(n2.rchild, n3)
        self.assertEqual(n3.parent, n2)

        self.assertEqual(n4.rchild, n6)
        self.assertEqual(n6.parent, n4)
        self.assertEqual(n6.lchild, n5)
        self.assertEqual(n5.parent, n6)
        self.assertEqual(n6.rchild, n7)
        self.assertEqual(n7.parent, n6)

        self.assertIsNone(n1.lchild)
        self.assertIsNone(n1.rchild)
        self.assertIsNone(n3.lchild)
        self.assertIsNone(n3.rchild)
        self.assertIsNone(n5.lchild)
        self.assertIsNone(n5.rchild)
        self.assertIsNone(n7.lchild)
        self.assertIsNone(n7.rchild)


    def test_find(self) -> None:
        self.t.insert(4, 2, 1, 3, 6, 5, 7)

        n4 = self.t.find(4)
        n2 = self.t.find(2)
        n1 = self.t.find(1)
        n3 = self.t.find(3)
        n6 = self.t.find(6)
        n5 = self.t.find(5)
        n7 = self.t.find(7)

        self.assertIsNotNone(n4)
        self.assertEqual(n4, 4)
        self.assertIsNone(n4.parent)
        self.assertEqual(n4, self.t.root)
        self.assertIsNotNone(n4.lchild)
        self.assertEqual(n4.lchild, n2)
        self.assertIsNotNone(n4.lchild.parent)
        self.assertEqual(n4.lchild.parent, n4)
        self.assertIsNotNone(n4.rchild)
        self.assertEqual(n4.rchild, n6)
        self.assertIsNotNone(n4.rchild.parent)
        self.assertEqual(n4.rchild.parent, n4)

        self.assertIsNotNone(n2)
        self.assertEqual(n2, 2)
        self.assertIsNotNone(n2.parent)
        self.assertEqual(n2.parent, n4)
        self.assertIsNotNone(n2.lchild)
        self.assertEqual(n2.lchild, n1)
        self.assertIsNotNone(n2.lchild.parent)
        self.assertEqual(n2.lchild.parent, n2)
        self.assertIsNotNone(n2.rchild)
        self.assertEqual(n2.rchild, n3)
        self.assertIsNotNone(n2.rchild.parent)
        self.assertEqual(n2.rchild.parent, n2)

        self.assertIsNotNone(n1)
        self.assertEqual(n1, 1)
        self.assertIsNotNone(n1.parent)
        self.assertEqual(n1.parent, n2)
        self.assertIsNone(n1.lchild)
        self.assertIsNone(n1.rchild)

        self.assertIsNotNone(n3)
        self.assertEqual(n3, 3)
        self.assertIsNotNone(n3.parent)
        self.assertEqual(n3.parent, n2)
        self.assertIsNone(n3.lchild)
        self.assertIsNone(n3.rchild)

        self.assertIsNotNone(n6)
        self.assertEqual(n6, 6)
        self.assertIsNotNone(n6.parent)
        self.assertEqual(n6.parent, n4)
        self.assertIsNotNone(n6.lchild)
        self.assertEqual(n6.lchild, n5)
        self.assertIsNotNone(n6.lchild.parent)
        self.assertEqual(n6.lchild.parent, n6)
        self.assertIsNotNone(n6.rchild)
        self.assertEqual(n6.rchild, n7)
        self.assertIsNotNone(n6.rchild.parent)
        self.assertEqual(n6.rchild.parent, n6)

        self.assertIsNotNone(n5)
        self.assertEqual(n5, 5)
        self.assertIsNotNone(n5.parent)
        self.assertEqual(n5.parent, n6)
        self.assertIsNone(n5.lchild)
        self.assertIsNone(n5.rchild)

        self.assertIsNotNone(n7)
        self.assertEqual(n7, 7)
        self.assertIsNotNone(n7.parent)
        self.assertEqual(n7.parent, n6)
        self.assertIsNone(n7.lchild)
        self.assertIsNone(n7.rchild)

        n8 = self.t.find(8)
        self.assertIsNone(n8)


    def test_delete(self) -> None:
        self.t.insert(4, 2, 6, 1, 3, 5, 7)

        self.assertTrue(self.t.delete(2))
        self.assertIsNone(self.t.find(2))
        self.assertEqual(self.t.root, 4)
        self.assertIsNotNone(self.t.root.lchild)
        self.assertEqual(self.t.root.lchild, 3)
        self.assertEqual(self.t.root.lchild.parent, 4)
        self.assertIsNone(self.t.root.lchild.rchild)

        self.assertTrue(self.t.delete(3))
        self.assertIsNone(self.t.find(3))
        self.assertEqual(self.t.root, 4)
        self.assertIsNotNone(self.t.root.lchild)
        self.assertEqual(self.t.root.lchild, 1)
        self.assertIsNotNone(self.t.root.lchild.parent, 4)

        self.assertTrue(self.t.delete(6))
        self.assertIsNone(self.t.find(6))
        self.assertEqual(self.t.root, 4)
        self.assertIsNotNone(self.t.root.rchild)
        self.assertEqual(self.t.root.rchild, 7)
        self.assertEqual(self.t.root.rchild.parent, 4)
        self.assertIsNone(self.t.root.rchild.rchild)

        self.assertTrue(self.t.delete(5))
        self.assertIsNone(self.t.find(5))
        self.assertEqual(self.t.root, 4)
        self.assertIsNone(self.t.root.rchild.rchild)
        self.assertIsNone(self.t.root.rchild.lchild)

        self.assertTrue(self.t.delete(4))
        self.assertIsNone(self.t.find(4))
        self.assertEqual(self.t.root, 7)
        self.assertIsNotNone(self.t.root.lchild)
        self.assertEqual(self.t.root.lchild, 1)
        self.assertIsNone(self.t.root.rchild)

        self.assertTrue(self.t.delete(7))
        self.assertIsNone(self.t.find(7))
        self.assertEqual(self.t.root, 1)

        self.assertTrue(self.t.delete(1))
        self.assertIsNone(self.t.find(1))
        self.assertIsNone(self.t.root)


    def test_delete_balanced(self) -> None:
        self.t.insert(4, 2, 6, 1, 3, 5, 7)
        self.assertTrue(self.t.delete(6))
        self.assertTrue(self.t.delete(5))
        self.assertTrue(self.t.delete(7))

        n4 = self.t.find(4)
        n2 = self.t.find(2)
        n6 = self.t.find(6)
        n1 = self.t.find(1)
        n3 = self.t.find(3)
        n5 = self.t.find(5)
        n7 = self.t.find(7)
        self.assertIsNotNone(n4)
        self.assertIsNotNone(n2)
        self.assertIsNotNone(n1)
        self.assertIsNotNone(n3)
        self.assertIsNone(n6)
        self.assertIsNone(n5)
        self.assertIsNone(n7)

        self.assertEqual(self.t.root, n2)
        self.assertEqual(n2.lchild, n1)
        self.assertEqual(n1.parent, n2)
        self.assertEqual(n2.rchild, n4)
        self.assertEqual(n4.parent, n2)
        self.assertEqual(n4.lchild, n3)
        self.assertEqual(n3.parent, n4)
        self.assertIsNone(n4.rchild)

        self.assertIsNone(n1.lchild)
        self.assertIsNone(n1.rchild)
        self.assertIsNone(n3.lchild)
        self.assertIsNone(n3.rchild)


    def test_traverse(self) -> None:
        self.t.insert(4, 2, 6, 1, 3, 5, 7)

        self.assertEqual([k for k in self.t.traverse('preorder')],
                         [4, 2, 1, 3, 6, 5, 7])
        self.assertEqual([k for k in self.t.traverse('inorder')],
                         [1, 2, 3, 4, 5, 6, 7])
        self.assertEqual([k for k in self.t.traverse('postorder')],
                         [1, 3, 2, 5, 7, 6, 4])
        self.assertEqual([k for k in self.t.traverse('level')],
                         [4, 2, 6, 1, 3, 5, 7])


    def test_rotate_ll_root(self) -> None:
        self.t.insert(2, 1, 4, 3, 6, 5, 7)
        # self.assertTrue(self.t._rotate(self.t.root))

        n2 = self.t.find(2)
        n1 = self.t.find(1)
        n4 = self.t.find(4)
        n3 = self.t.find(3)
        n6 = self.t.find(6)
        n5 = self.t.find(5)
        n7 = self.t.find(7)
        self.assertIsNotNone(n2)
        self.assertIsNotNone(n1)
        self.assertIsNotNone(n4)
        self.assertIsNotNone(n3)
        self.assertIsNotNone(n6)
        self.assertIsNotNone(n5)
        self.assertIsNotNone(n7)

        self.assertEqual(self.t.root, n4)

        self.assertEqual(n4.lchild, n2)
        self.assertEqual(n2.parent, n4)
        self.assertEqual(n2.lchild, n1)
        self.assertEqual(n1.parent, n2)
        self.assertEqual(n2.rchild, n3)
        self.assertEqual(n3.parent, n2)

        self.assertEqual(n4.rchild, n6)
        self.assertEqual(n6.parent, n4)
        self.assertEqual(n6.lchild, n5)
        self.assertEqual(n5.parent, n6)
        self.assertEqual(n6.rchild, n7)
        self.assertEqual(n7.parent, n6)

        self.assertIsNone(n1.lchild)
        self.assertIsNone(n1.rchild)
        self.assertIsNone(n3.lchild)
        self.assertIsNone(n3.rchild)
        self.assertIsNone(n5.lchild)
        self.assertIsNone(n5.rchild)
        self.assertIsNone(n7.lchild)
        self.assertIsNone(n7.rchild)


    def test_rotate_ll_nonroot(self) -> None:
        self.t.insert(5, 3, 7, 1, 4, 6, 9, 2, 8, 10, 11)
        # self.assertTrue(self.t._rotate(self.t.root.rchild))

        n5 = self.t.find(5)
        n3 = self.t.find(3)
        n7 = self.t.find(7)
        n1 = self.t.find(1)
        n4 = self.t.find(4)
        n6 = self.t.find(6)
        n9 = self.t.find(9)
        n2 = self.t.find(2)
        n8 = self.t.find(8)
        n10 = self.t.find(10)
        n11 = self.t.find(11)
        self.assertIsNotNone(n5)
        self.assertIsNotNone(n3)
        self.assertIsNotNone(n7)
        self.assertIsNotNone(n1)
        self.assertIsNotNone(n4)
        self.assertIsNotNone(n6)
        self.assertIsNotNone(n9)
        self.assertIsNotNone(n2)
        self.assertIsNotNone(n8)
        self.assertIsNotNone(n10)
        self.assertIsNotNone(n11)

        self.assertEqual(self.t.root, n5)

        self.assertEqual(n5.lchild, n3)
        self.assertEqual(n3.parent, n5)
        self.assertEqual(n3.lchild, n1)
        self.assertEqual(n1.parent, n3)
        self.assertIsNone(n1.lchild)
        self.assertEqual(n1.rchild, n2)
        self.assertEqual(n2.parent, n1)
        self.assertEqual(n3.rchild, n4)
        self.assertEqual(n4.parent, n3)
        self.assertIsNone(n4.lchild)
        self.assertIsNone(n4.rchild)

        self.assertEqual(n5.rchild, n9)
        self.assertEqual(n9.parent, n5)
        self.assertEqual(n9.lchild, n7)
        self.assertEqual(n7.parent, n9)
        self.assertEqual(n7.lchild, n6)
        self.assertEqual(n6.parent, n7)
        self.assertEqual(n7.rchild, n8)
        self.assertEqual(n8.parent, n7)
        self.assertEqual(n9.rchild, n10)
        self.assertEqual(n10.parent, n9)
        self.assertIsNone(n10.lchild)
        self.assertEqual(n10.rchild, n11)
        self.assertEqual(n11.parent, n10)


    def test_rotate_rr_root(self) -> None:
        self.t.insert(6, 4, 7, 2, 5, 1, 3)
        # self.assertTrue(self.t._rotate(self.t.root))

        n6 = self.t.find(6)
        n4 = self.t.find(4)
        n7 = self.t.find(7)
        n2 = self.t.find(2)
        n5 = self.t.find(5)
        n1 = self.t.find(1)
        n3 = self.t.find(3)
        self.assertIsNotNone(n6)
        self.assertIsNotNone(n4)
        self.assertIsNotNone(n7)
        self.assertIsNotNone(n2)
        self.assertIsNotNone(n5)
        self.assertIsNotNone(n1)
        self.assertIsNotNone(n3)

        self.assertEqual(self.t.root, n4)

        self.assertEqual(n4.lchild, n2)
        self.assertEqual(n2.parent, n4)
        self.assertEqual(n2.lchild, n1)
        self.assertEqual(n1.parent, n2)
        self.assertEqual(n2.rchild, n3)
        self.assertEqual(n3.parent, n2)

        self.assertEqual(n4.rchild, n6)
        self.assertEqual(n6.parent, n4)
        self.assertEqual(n6.lchild, n5)
        self.assertEqual(n5.parent, n6)
        self.assertEqual(n6.rchild, n7)
        self.assertEqual(n7.parent, n6)

        self.assertIsNone(n1.lchild)
        self.assertIsNone(n1.rchild)
        self.assertIsNone(n3.lchild)
        self.assertIsNone(n3.rchild)
        self.assertIsNone(n5.lchild)
        self.assertIsNone(n5.rchild)
        self.assertIsNone(n7.lchild)
        self.assertIsNone(n7.rchild)


    def test_rotate_rr_nonroot(self) -> None:
        self.t.insert(7, 5, 9, 3, 6, 8, 11, 2, 4, 10, 1)
        # self.assertTrue(self.t._rotate(self.t.root.lchild))

        n7 = self.t.find(7)
        n5 = self.t.find(5)
        n9 = self.t.find(9)
        n3 = self.t.find(3)
        n6 = self.t.find(6)
        n8 = self.t.find(8)
        n11 = self.t.find(11)
        n2 = self.t.find(2)
        n4 = self.t.find(4)
        n10 = self.t.find(10)
        n1 = self.t.find(1)
        self.assertIsNotNone(7)
        self.assertIsNotNone(5)
        self.assertIsNotNone(9)
        self.assertIsNotNone(3)
        self.assertIsNotNone(6)
        self.assertIsNotNone(8)
        self.assertIsNotNone(11)
        self.assertIsNotNone(2)
        self.assertIsNotNone(4)
        self.assertIsNotNone(10)
        self.assertIsNotNone(1)

        self.assertEqual(self.t.root, n7)

        self.assertEqual(n7.lchild, n3)
        self.assertEqual(n3.parent, n7)
        self.assertEqual(n7.rchild, n9)
        self.assertEqual(n9.parent, n7)
        self.assertEqual(n3.lchild, n2)
        self.assertEqual(n2.parent, n3)
        self.assertEqual(n3.rchild, n5)
        self.assertEqual(n5.parent, n3)
        self.assertEqual(n9.lchild, n8)
        self.assertEqual(n8.parent, n9)
        self.assertEqual(n9.rchild, n11)
        self.assertEqual(n11.parent, n9)
        self.assertEqual(n2.lchild, n1)
        self.assertEqual(n1.parent, n2)
        self.assertIsNone(n2.rchild)
        self.assertEqual(n5.lchild, n4)
        self.assertEqual(n4.parent, n5)
        self.assertEqual(n5.rchild, n6)
        self.assertEqual(n6.parent, n5)
        self.assertIsNone(n8.lchild)
        self.assertIsNone(n8.rchild)
        self.assertEqual(n11.lchild, n10)
        self.assertEqual(n10.parent, n11)
        self.assertIsNone(n11.rchild)


    def test_rotate_lr_root(self) -> None:
        self.t.insert(6, 2, 7, 1, 4, 3, 5)
        # self.assertTrue(self.t._rotate(self.t.root))

        n6 = self.t.find(6)
        n2 = self.t.find(2)
        n7 = self.t.find(7)
        n1 = self.t.find(1)
        n4 = self.t.find(4)
        n3 = self.t.find(3)
        n5 = self.t.find(5)
        self.assertIsNotNone(n6)
        self.assertIsNotNone(n2)
        self.assertIsNotNone(n7)
        self.assertIsNotNone(n1)
        self.assertIsNotNone(n4)
        self.assertIsNotNone(n3)
        self.assertIsNotNone(n5)

        self.assertEqual(self.t.root, n4)

        self.assertEqual(n4.lchild, n2)
        self.assertEqual(n2.parent, n4)
        self.assertEqual(n2.lchild, n1)
        self.assertEqual(n1.parent, n2)
        self.assertEqual(n2.rchild, n3)
        self.assertEqual(n3.parent, n2)

        self.assertEqual(n4.rchild, n6)
        self.assertEqual(n6.parent, n4)
        self.assertEqual(n6.lchild, n5)
        self.assertEqual(n5.parent, n6)
        self.assertEqual(n6.rchild, n7)
        self.assertEqual(n7.parent, n6)

        self.assertIsNone(n1.lchild)
        self.assertIsNone(n1.rchild)
        self.assertIsNone(n3.lchild)
        self.assertIsNone(n3.rchild)
        self.assertIsNone(n5.lchild)
        self.assertIsNone(n5.rchild)
        self.assertIsNone(n7.lchild)
        self.assertIsNone(n7.rchild)


    def test_rotate_lr_nonroot(self) -> None:
        self.t.insert(8, 6, 10, 2, 7, 9, 12, 1, 4, 11, 3, 5)
        # self.assertTrue(self.t._rotate(self.t.root.lchild))

        n8 = self.t.find(8)
        n6 = self.t.find(6)
        n10 = self.t.find(10)
        n2 = self.t.find(2)
        n7 = self.t.find(7)
        n9 = self.t.find(9)
        n12 = self.t.find(12)
        n1 = self.t.find(1)
        n4 = self.t.find(4)
        n11 = self.t.find(11)
        n3 = self.t.find(3)
        n5 = self.t.find(5)
        self.assertIsNotNone(n8)
        self.assertIsNotNone(n6)
        self.assertIsNotNone(n10)
        self.assertIsNotNone(n2)
        self.assertIsNotNone(n7)
        self.assertIsNotNone(n9)
        self.assertIsNotNone(n12)
        self.assertIsNotNone(n1)
        self.assertIsNotNone(n4)
        self.assertIsNotNone(n11)
        self.assertIsNotNone(n3)
        self.assertIsNotNone(n5)

        self.assertEqual(self.t.root, n8)

        self.assertEqual(n8.lchild, n4)
        self.assertEqual(n4.parent, n8)
        self.assertEqual(n4.lchild, n2)
        self.assertEqual(n2.parent, n4)
        self.assertEqual(n2.lchild, n1)
        self.assertEqual(n1.parent, n2)
        self.assertEqual(n2.rchild, n3)
        self.assertEqual(n3.parent, n2)
        self.assertEqual(n4.rchild, n6)
        self.assertEqual(n6.parent, n4)
        self.assertEqual(n6.lchild, n5)
        self.assertEqual(n5.parent, n6)
        self.assertEqual(n6.rchild, n7)
        self.assertEqual(n7.parent, n6)

        self.assertEqual(n8.rchild, n10)
        self.assertEqual(n10.parent, n8)
        self.assertEqual(n10.lchild, n9)
        self.assertEqual(n9.parent, n10)
        self.assertEqual(n10.rchild, n12)
        self.assertEqual(n12.parent, n10)
        self.assertEqual(n12.lchild, n11)
        self.assertEqual(n11.parent, n12)
        self.assertIsNone(n12.rchild)

        self.assertIsNone(n1.lchild)
        self.assertIsNone(n1.rchild)
        self.assertIsNone(n3.lchild)
        self.assertIsNone(n3.rchild)
        self.assertIsNone(n5.lchild)
        self.assertIsNone(n5.rchild)
        self.assertIsNone(n9.lchild)
        self.assertIsNone(n9.rchild)
        self.assertIsNone(n11.lchild)
        self.assertIsNone(n11.rchild)


    def test_rotate_rl_root(self) -> None:
        self.t.insert(2, 1, 6, 4, 7, 3, 5)
        # self.assertTrue(self.t._rotate(self.t.root))

        n2 = self.t.find(2)
        n1 = self.t.find(1)
        n6 = self.t.find(6)
        n4 = self.t.find(4)
        n7 = self.t.find(7)
        n3 = self.t.find(3)
        n5 = self.t.find(5)
        self.assertIsNotNone(n2)
        self.assertIsNotNone(n1)
        self.assertIsNotNone(n6)
        self.assertIsNotNone(n4)
        self.assertIsNotNone(n7)
        self.assertIsNotNone(n3)
        self.assertIsNotNone(n5)

        self.assertEqual(self.t.root, n4)

        self.assertEqual(n4.lchild, n2)
        self.assertEqual(n2.parent, n4)
        self.assertEqual(n2.lchild, n1)
        self.assertEqual(n1.parent, n2)
        self.assertEqual(n2.rchild, n3)
        self.assertEqual(n3.parent, n2)

        self.assertEqual(n4.rchild, n6)
        self.assertEqual(n6.parent, n4)
        self.assertEqual(n6.lchild, n5)
        self.assertEqual(n5.parent, n6)
        self.assertEqual(n6.rchild, n7)
        self.assertEqual(n7.parent, n6)

        self.assertIsNone(n1.lchild)
        self.assertIsNone(n1.rchild)
        self.assertIsNone(n3.lchild)
        self.assertIsNone(n3.rchild)
        self.assertIsNone(n5.lchild)
        self.assertIsNone(n5.rchild)
        self.assertIsNone(n7.lchild)
        self.assertIsNone(n7.rchild)


    def test_rotate_rl_nonroot(self) -> None:
        self.t.insert(5, 3, 7, 1, 4, 6, 11, 2, 9, 12, 8, 10)
        # self.assertTrue(self.t._rotate(self.t.root.rchild))

        n5 = self.t.find(5)
        n3 = self.t.find(3)
        n7 = self.t.find(7)
        n1 = self.t.find(1)
        n4 = self.t.find(4)
        n6 = self.t.find(6)
        n11 = self.t.find(11)
        n2 = self.t.find(2)
        n9 = self.t.find(9)
        n12 = self.t.find(12)
        n8 = self.t.find(8)
        n10 = self.t.find(10)
        self.assertIsNotNone(n5)
        self.assertIsNotNone(n3)
        self.assertIsNotNone(n7)
        self.assertIsNotNone(n1)
        self.assertIsNotNone(n4)
        self.assertIsNotNone(n6)
        self.assertIsNotNone(n11)
        self.assertIsNotNone(n2)
        self.assertIsNotNone(n9)
        self.assertIsNotNone(n12)
        self.assertIsNotNone(n8)
        self.assertIsNotNone(n10)

        self.assertEqual(self.t.root, n5)

        self.assertEqual(n5.lchild, n3)
        self.assertEqual(n3.parent, n5)
        self.assertEqual(n3.lchild, n1)
        self.assertEqual(n1.parent, n3)
        self.assertIsNone(n1.lchild)
        self.assertEqual(n1.rchild, n2)
        self.assertEqual(n2.parent, n1)
        self.assertEqual(n3.rchild, n4)
        self.assertEqual(n4.parent, n3)

        self.assertEqual(n5.rchild, n9)
        self.assertEqual(n9.parent, n5)
        self.assertEqual(n9.lchild, n7)
        self.assertEqual(n7.parent, n9)
        self.assertEqual(n7.lchild, n6)
        self.assertEqual(n6.parent, n7)
        self.assertEqual(n7.rchild, n8)
        self.assertEqual(n8.parent, n7)
        self.assertEqual(n9.rchild, n11)
        self.assertEqual(n11.parent, n9)
        self.assertEqual(n11.lchild, n10)
        self.assertEqual(n10.parent, n11)
        self.assertEqual(n11.rchild, n12)
        self.assertEqual(n12.parent, n11)

        self.assertIsNone(n2.lchild)
        self.assertIsNone(n2.rchild)
        self.assertIsNone(n6.lchild)
        self.assertIsNone(n6.rchild)
        self.assertIsNone(n8.lchild)
        self.assertIsNone(n8.rchild)
        self.assertIsNone(n10.lchild)
        self.assertIsNone(n10.rchild)
        self.assertIsNone(n12.lchild)
        self.assertIsNone(n12.rchild)


if __name__ == '__main__':
    unittest.main()
